### ISSUE TITLE
8bit grayscale now loaded as RGB

### ISSUE THREAD

**Issue by petsuter** [imageio/imageio#1032]
Hi,

Example file: https://github.com/sondrele/rust-bmp/raw/master/test/bmpsuite-2.5/g/pal8gs.bmp

Such grayscale images are now loaded as RGB:
```
>>> import imageio
>>> imageio.imread("pal8gs.bmp").shape
(64, 127, 3)
>>> imageio.__version__
'2.31.1'
```

They used to be loaded as grayscale:
```
>>> import imageio
>>> imageio.imread("pal8gs.bmp").shape
(64, 127)
>>> imageio.__version__
'2.6.1'
````

Is this a bug / intended? Can it be disabled / controlled somehow?

Thanks.

**Comment by FirefoxMetzger** [comment]
Interesting find, thanks for the report @petsuter . I'll try to have a look tomorrow and see if I can find the reason for the behavior change.

In the meantime, you can "force" a grayscale result by using:

```python
>>> import imageio.v3 as iio
>>> iio.imread("https://github.com/sondrele/rust-bmp/raw/master/test/bmpsuite-2.5/g/pal8gs.bmp", mode="L").shape
(64, 127)
```

**Comment by petsuter** [comment]
Thanks, that's very helpful to know. :+1: Is that documented somewhere? Is it specific to Pillow?

----

As far as I can tell:
* The change happened from imageio  2.27.0 to 2.28.0
* In 2.6.1 [this is the relevant old code](https://github.com/imageio/imageio/blob/v2.6.1/imageio/plugins/pillow.py#L722):
```
    elif im.mode == "P" and is_gray:
        # Paletted images that are already gray by their palette
        # are converted so that the resulting numpy array is 2D.
        frame = im.convert("L")
```
* In 2.27.0 that code is in [pillow_legacy](https://github.com/imageio/imageio/blob/v2.27.0/imageio/plugins/pillow_legacy.py#L700).
* In 2.31.1 [this is the relevant new code](https://github.com/imageio/imageio/blob/v2.31.1/imageio/plugins/pillow.py#L278):
```
        elif image.mode == "P":
            # adjust for pillow9 changes
            # see: https://github.com/python-pillow/Pillow/issues/5929
            image = image.convert(image.palette.mode)
```
(Where `image.palette.mode` is 'RGB'.)

So maybe this changed because the legacy Pillow plugin is not used anymore, maybe since #824 (mentioned as [the change of v2.28.0](https://github.com/imageio/imageio/blob/master/CHANGELOG.md#v2280-2023-04-24))?

**Comment by petsuter** [comment]
I'd also like to read 16 bit grayscale images in the same code. Example: https://github.com/lunapaint/pngsuite/blob/main/png/basi0g16.png
```python
>>> imageio.v3.imread("basi0g16.png").dtype
dtype('int32')
>>> imageio.v3.imread("basi0g16.png", mode="L").dtype
dtype('uint8')
>>> imageio.v3.imread("basi0g16.png", mode="I").dtype
dtype('int32')
>>> imageio.v3.imread("basi0g16.png", mode="I;16").dtype
dtype('uint16')
>>> imageio.v3.improps("basi0g16.png")
ImageProperties(shape=(32, 32), dtype=dtype('int32'), n_images=None, is_batch=False, spacing=None)
>>> imageio.v3.immeta("basi0g16.png")
{'interlace': 1, 'gamma': 1.0, 'mode': 'I', 'shape': (32, 32)}
```

So using `mode="L"` would be problematic; `mode="I;16"` would be required there.
Would I have to try "I;16" first and fallback to "L", or is there a better way? Thanks.

**Comment by petsuter** [comment]
```
Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    imageio.v3.imread(r"test.tif", mode="L")
  File "C:\Python311\site-packages\imageio\v3.py", line 54, in imread
    return np.asarray(img_file.read(**call_kwargs))
  File "C:\Python311\site-packages\imageio\plugins\tifffile_v3.py", line 189, in read
    ndimage = self._fh.asarray(series=index, **kwargs)
TypeError: TiffFile.asarray() got an unexpected keyword argument 'mode'
```
Is `mode` backend specific? Is there a generic way?
Thanks.

**Comment by Pandede** [comment]
> ```
> Traceback (most recent call last):
>   File "<pyshell#4>", line 1, in <module>
>     imageio.v3.imread(r"test.tif", mode="L")
>   File "C:\Python311\site-packages\imageio\v3.py", line 54, in imread
>     return np.asarray(img_file.read(**call_kwargs))
>   File "C:\Python311\site-packages\imageio\plugins\tifffile_v3.py", line 189, in read
>     ndimage = self._fh.asarray(series=index, **kwargs)
> TypeError: TiffFile.asarray() got an unexpected keyword argument 'mode'
> ```
> 
> Is `mode` backend specific? Is there a generic way? Thanks.

You may change the plugin to read the image:
```
imageio.v3.imread('test.tif', mode='L', plugin='pillow')
```
