### ISSUE TITLE
2.31.4: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [imageio/imageio#1038]
I'm using below patch to allow build documentation without have `imageio` module installed
```patch
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -13,6 +13,8 @@

 import sys
 import os
+sys.path.insert(0, os.path.abspath(".."))
+
 import imageio
 import inspect
 import importlib
```
(please let me know if you want above as PR).

Looks like documentation build fails with:
<details>

```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v7.0.1
making output directory... done
[autosummary] generating autosummary for: development/index.rst, development/plugins.rst, examples.rst, formats/formats_by_plugin.rst, formats/index.rst, formats/video_formats.rst, index.rst, reference/core_v3.rst, reference/index.rst, reference/userapi.rst, user_guide/cmdlinescripts.rst, user_guide/drop27.rst, user_guide/envvariables.rst, user_guide/freezing.rst, user_guide/index.rst, user_guide/installation.rst, user_guide/overview.rst, user_guide/requests.rst, user_guide/scipy.rst, user_guide/standardimages.rst
[autosummary] generating autosummary for: /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.core.Format.__init__.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.core.Format._can_read.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.core.Format._can_write.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.core.Format.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.core.Request.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.core.v3_plugin_api.ImageProperties.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.core.v3_plugin_api.PluginV3.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.bsdf.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.dicom.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.feisem.rst, ..., /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.v2.mvolread.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.v2.mvolwrite.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.v2.volread.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.v2.volwrite.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.v3.imiter.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.v3.immeta.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.v3.imopen.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.v3.improps.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.v3.imread.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.v3.imwrite.rst
[autosummary] generating autosummary for: /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/_plugins/pillow/imageio.plugins.pillow.PillowPlugin.get_meta.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/_plugins/pillow/imageio.plugins.pillow.PillowPlugin.iter.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/_plugins/pillow/imageio.plugins.pillow.PillowPlugin.read.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/_plugins/pillow/imageio.plugins.pillow.PillowPlugin.write.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.opencv.OpenCVPlugin.iter.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.opencv.OpenCVPlugin.metadata.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.opencv.OpenCVPlugin.properties.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.opencv.OpenCVPlugin.read.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.opencv.OpenCVPlugin.write.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.pyav.PyAVPlugin.container_metadata.rst, ..., /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.spe.SpePlugin.iter.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.spe.SpePlugin.metadata.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.spe.SpePlugin.properties.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.spe.SpePlugin.read.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.iter.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.iter_pages.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.metadata.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.properties.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.read.rst, /home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/_autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.write.rst
building [mo]: targets for 0 po files that are out of date
writing output...
building [man]: all manpages
updating environment: [new config] 88 added, 0 changed, 0 removed
reading sources... [  1%] _autosummary/_plugins/pillow/imageio.plugins.pillow.PillowPlugin.get_meta
reading sources... [  2%] _autosummary/_plugins/pillow/imageio.plugins.pillow.PillowPlugin.iter
reading sources... [  3%] _autosummary/_plugins/pillow/imageio.plugins.pillow.PillowPlugin.read
reading sources... [  4%] _autosummary/_plugins/pillow/imageio.plugins.pillow.PillowPlugin.write
reading sources... [  5%] _autosummary/imageio.core.Format
reading sources... [  6%] _autosummary/imageio.core.Format.__init__
reading sources... [  7%] _autosummary/imageio.core.Format._can_read
reading sources... [  9%] _autosummary/imageio.core.Format._can_write
reading sources... [ 10%] _autosummary/imageio.core.Request
reading sources... [ 11%] _autosummary/imageio.core.v3_plugin_api.ImageProperties
reading sources... [ 12%] _autosummary/imageio.core.v3_plugin_api.PluginV3
reading sources... [ 13%] _autosummary/imageio.plugins.bsdf
reading sources... [ 14%] _autosummary/imageio.plugins.dicom
reading sources... [ 15%] _autosummary/imageio.plugins.feisem
reading sources... [ 17%] _autosummary/imageio.plugins.ffmpeg
reading sources... [ 18%] _autosummary/imageio.plugins.fits
reading sources... [ 19%] _autosummary/imageio.plugins.freeimage
reading sources... [ 20%] _autosummary/imageio.plugins.gdal
reading sources... [ 21%] _autosummary/imageio.plugins.lytro
reading sources... [ 22%] _autosummary/imageio.plugins.npz
reading sources... [ 23%] _autosummary/imageio.plugins.opencv
reading sources... [ 25%] _autosummary/imageio.plugins.opencv.OpenCVPlugin.iter
reading sources... [ 26%] _autosummary/imageio.plugins.opencv.OpenCVPlugin.metadata
reading sources... [ 27%] _autosummary/imageio.plugins.opencv.OpenCVPlugin.properties
reading sources... [ 28%] _autosummary/imageio.plugins.opencv.OpenCVPlugin.read
reading sources... [ 29%] _autosummary/imageio.plugins.opencv.OpenCVPlugin.write
reading sources... [ 30%] _autosummary/imageio.plugins.pillow
reading sources... [ 31%] _autosummary/imageio.plugins.pillow_legacy
reading sources... [ 32%] _autosummary/imageio.plugins.pyav
reading sources... [ 34%] _autosummary/imageio.plugins.pyav.PyAVPlugin.container_metadata
reading sources... [ 35%] _autosummary/imageio.plugins.pyav.PyAVPlugin.init_video_stream
reading sources... [ 36%] _autosummary/imageio.plugins.pyav.PyAVPlugin.iter
reading sources... [ 37%] _autosummary/imageio.plugins.pyav.PyAVPlugin.metadata
reading sources... [ 38%] _autosummary/imageio.plugins.pyav.PyAVPlugin.properties
reading sources... [ 39%] _autosummary/imageio.plugins.pyav.PyAVPlugin.read
reading sources... [ 40%] _autosummary/imageio.plugins.pyav.PyAVPlugin.set_video_filter
reading sources... [ 42%] _autosummary/imageio.plugins.pyav.PyAVPlugin.video_stream_metadata
reading sources... [ 43%] _autosummary/imageio.plugins.pyav.PyAVPlugin.write
reading sources... [ 44%] _autosummary/imageio.plugins.pyav.PyAVPlugin.write_frame
reading sources... [ 45%] _autosummary/imageio.plugins.simpleitk
reading sources... [ 46%] _autosummary/imageio.plugins.spe
reading sources... [ 47%] _autosummary/imageio.plugins.spe.SpePlugin.iter
reading sources... [ 48%] _autosummary/imageio.plugins.spe.SpePlugin.metadata
reading sources... [ 50%] _autosummary/imageio.plugins.spe.SpePlugin.properties
reading sources... [ 51%] _autosummary/imageio.plugins.spe.SpePlugin.read
reading sources... [ 52%] _autosummary/imageio.plugins.swf
reading sources... [ 53%] _autosummary/imageio.plugins.tifffile
reading sources... [ 54%] _autosummary/imageio.plugins.tifffile_v3
reading sources... [ 55%] _autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.iter
reading sources... [ 56%] _autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.iter_pages
reading sources... [ 57%] _autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.metadata
reading sources... [ 59%] _autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.properties
reading sources... [ 60%] _autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.read
reading sources... [ 61%] _autosummary/imageio.plugins.tifffile_v3.TifffilePlugin.write
reading sources... [ 62%] _autosummary/imageio.v2.imread
reading sources... [ 63%] _autosummary/imageio.v2.imwrite
reading sources... [ 64%] _autosummary/imageio.v2.mimread
reading sources... [ 65%] _autosummary/imageio.v2.mimwrite
reading sources... [ 67%] _autosummary/imageio.v2.mvolread
reading sources... [ 68%] _autosummary/imageio.v2.mvolwrite
reading sources... [ 69%] _autosummary/imageio.v2.volread
reading sources... [ 70%] _autosummary/imageio.v2.volwrite
reading sources... [ 71%] _autosummary/imageio.v3.imiter
reading sources... [ 72%] _autosummary/imageio.v3.immeta
reading sources... [ 73%] _autosummary/imageio.v3.imopen
reading sources... [ 75%] _autosummary/imageio.v3.improps
reading sources... [ 76%] _autosummary/imageio.v3.imread
reading sources... [ 77%] _autosummary/imageio.v3.imwrite
reading sources... [ 78%] development/index
reading sources... [ 79%] development/plugins

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/tkloczko/rpmbuild/BUILD/imageio-2.31.4/docs/imageio_ext.py", line 55, in rstjinja
    rendered = app.builder.templates.render_string(
AttributeError: 'ManualPageBuilder' object has no attribute 'templates'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app.build(args.force_all, args.filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 351, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 291, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 495, in read_doc
    publisher.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 234, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 103, in read
    self.input = self.read_source(settings.env)
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 113, in read_source
    env.events.emit('source-read', env.docname, arg)
  File "/usr/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function rstjinja at 0x7fb29766b5e0> for event 'source-read' threw an exception (exception: 'ManualPageBuilder' object has no attribute 'templates')

Extension error (imageio_ext):
Handler <function rstjinja at 0x7fb29766b5e0> for event 'source-read' threw an exception (exception: 'ManualPageBuilder' object has no attribute 'templates')
```
</details>

**Comment by kloczek** [comment]
gentle ping .. any update? 🤔
