### ISSUE TITLE
Bug with PyAV plugin

### ISSUE THREAD

**Issue by johnathanchiu** [imageio/imageio#1099]
Running the snippet below results in the following error. I am currently using version `imageio==2.34.2`. 

Error:
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    for i, im in enumerate(reader):
  File "~/anaconda3/envs/yt-clipper/lib/python3.11/site-packages/imageio/v2.py", line 166, in iter_data
    metadata = self.instance.metadata(index=idx, exclude_applied=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/anaconda3/envs/yt-clipper/lib/python3.11/site-packages/imageio/plugins/pyav.py", line 771, in metadata
    {item.type.name: item.to_bytes() for item in desired_frame.side_data}
  File "~/anaconda3/envs/yt-clipper/lib/python3.11/site-packages/imageio/plugins/pyav.py", line 771, in <dictcomp>
    {item.type.name: item.to_bytes() for item in desired_frame.side_data}
                     ^^^^^^^^^^^^^
AttributeError: 'av.sidedata.sidedata.SideData' object has no attribute 'to_bytes'
```

Snippet:
```
import imageio as iio

video_path = 'test_video_file.ts'
reader = iio.get_reader(video_path)
for i, im in enumerate(reader):
    break
```

**Comment by hmaarrfk** [comment]
can likely be closed right

**Comment by FirefoxMetzger** [comment]
Yes, good find @hmaarrfk !
