### ISSUE TITLE
Core dumped when reading gifs with get_reader

### ISSUE THREAD

**Issue by ProgrammerPeter** [imageio/imageio#1105]
My code:
"""
with imageio.get_reader("/path/to/gif") as reader: 
    for image in reader.iter_data():
        pass
"""

After it reads some images normally, it core dumped with the following traceback:
"""
#0  0x0000ffffbb73af14 in ?? () from /lib/aarch64-linux-gnu/libc.so.6
#1  0x0000ffffbac802a4 in _contig_to_contig ()
   from /path/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-aarch64-linux-gnu.so
#2  0x0000ffffbad0e8fc in raw_array_assign_array ()
   from /path/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-aarch64-linux-gnu.so
#3  0x0000ffffbad0f374 in PyArray_AssignArray ()
   from /path/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-aarch64-linux-gnu.so
#4  0x0000ffffbad1c888 in PyArray_NewCopy ()
   from /path/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-aarch64-linux-gnu.so
#5  0x0000ffffbad73f2c in array_array ()
   from /path/python3.9/site-packages/numpy/core/_multiarray_umath.cpython-39-aarch64-linux-gnu.so
"""

I alse use py-bt to get the python traceback:
![image](https://github.com/user-attachments/assets/c1e9b860-8f90-4fed-9a60-15fbf1bbbcd4)

It seems that something went wrong while copying the numpy array.

Python version: 3.9.19
ImageIO version: 2.34.2
NumPy verison: 1.26.4

**Comment by Pandede** [comment]
I'm trying to reproduce the error but failed:
```python
import imageio.v2 as iio

with iio.get_reader(".test_images/newtonscradle.gif") as reader:
    for image in reader.iter_data():
        print(image.shape)
```
May you provides the GIF?

**Comment by ProgrammerPeter** [comment]
> I'm trying to reproduce the error but it works fine:
> 
> ```python
> import imageio.v2 as iio
> 
> with iio.get_reader(".test_images/newtonscradle.gif") as reader:
>     for image in reader.iter_data():
>         print(image.shape)
> ```
> 
> May you provides the GIF?

I think the problem may have nothing to do with the particular picture as it is occasional.
I change to load gif with PIL and the problem is gone.
