### ISSUE TITLE
Issue with avconv

### ISSUE THREAD

**Issue by cancan101** [imageio/imageio#170]
I am using `avconv` (`apt-get install libav-tools` and then `IMAGEIO_FFMPEG_EXE=avconv`) but then when trying to open:

```
iter(imageio.get_reader('http://www.quirksmode.org/html5/videos/big_buck_bunny.mp4', format='MP4')).next()
```

I get:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/imageio/core/format.py", line 375, in iter_data
    im, meta = self._get_data(i)
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 326, in _get_data
    result = self._read_frame()
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 526, in _read_frame
    s = self._read_frame_data()
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 512, in _read_frame_data
    raise RuntimeError(fmt % (err1, err2))
RuntimeError: Could not read frame:

=== stderr ===
avconv version 11.8-6:11.8-1~deb8u1, Copyright (c) 2000-2016 the Libav developers
  built on Oct  1 2016 07:16:29 with gcc 4.9.2 (Debian 4.9.2-10)
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x142b4c0] max_analyze_duration 5000000 reached
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/imageio_5oLdgO.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp42avc1
    creation_time   : 2010-02-09 01:55:39
  Duration: 00:01:00.13, start: 0.000000, bitrate: 733 kb/s
    Stream #0.0(eng): Audio: aac, 22050 Hz, stereo, fltp, 65 kb/s (default)
    Metadata:
      creation_time   : 2010-02-09 01:55:39
    Stream #0.1(eng): Video: h264 (Constrained Baseline), yuv420p, 640x360, 612 kb/s, 24 fps, 600 tbn (default)
    Metadata:
      creation_time   : 2010-02-09 01:55:39
    Stream #0.2(eng): Data: rtp  / 0x20707472, 45 kb/s
    Metadata:
      creation_time   : 2010-02-09 01:55:39
    Stream #0.3(eng): Data: rtp  / 0x20707472, 5 kb/s
    Metadata:
      creation_time   : 2010-02-09 01:55:39
Output #0, image2pipe, to 'pipe:':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp42avc1
    creation_time   : 2010-02-09 01:55:39
    encoder         : Lavf56.1.0
    Stream #0.0(eng): Video: rawvideo, rgb24, 640x360, q=2-31, 200 kb/s, 600 tbn, 600 tbc (default)
    Metadata:
      creation_time   : 2010-02-09 01:55:39
      encoder         : Lavc56.1.0 rawvideo
Stream mapping:
  Stream #0:1 -> #0:0 (h264 (native) -> rawvideo (native))
Press ctrl-c to stop encoding
```

This does work fine if I use the ffmpeg binary that imageio downloads.

**Comment by almarklein** [comment]
Mmm, that error is not very helpful, except that it seems like avconv does not have any problems, so it might be the reading at the imageio side that goes wrong. It seems like it tries to print info from an exception object, but it does not show anything, which is weird: https://github.com/imageio/imageio/blob/master/imageio/plugins/ffmpeg.py#L499-L512

Care to dive in and see what the actual problem is?  One possible cause might be that avconv has  a slightly differtent "header" so that imageio parses it incorrectly and thus uses an incorrect frame size or something.

**Comment by almarklein** [comment]
Marking this as a diplicate of #171
