### ISSUE TITLE
imread AttributeError: close

### ISSUE THREAD

**Issue by gsb-eng** [imageio/imageio#216]
I'm trying to read an image using `imread`, but it is giving AttributeError.

```
>>> from imageio import imread
>>> imread('/tmp/tmpl01_nq2g.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gsb-eng/prog/py3-envs/fd/lib/python3.5/site-packages/imageio/core/functions.py", line 187, in imread
    return reader.get_data(0)
  File "/home/gsb-eng/prog/py3-envs/fd/lib/python3.5/site-packages/imageio/core/format.py", line 232, in __exit__
    self.close() 
  File "/home/gsb-eng/prog/py3-envs/fd/lib/python3.5/site-packages/imageio/core/format.py", line 247, in close
    self._close()
  File "/home/gsb-eng/prog/py3-envs/fd/lib/python3.5/site-packages/imageio/plugins/pillow.py", line 93, in _close
    self._im.close()
  File "/home/gsb-eng/prog/py3-envs/fd/lib/python3.5/site-packages/PIL/Image.py", line 489, in __getattr__
    raise AttributeError(name)
AttributeError: close
```

**Comment by gsb-eng** [comment]
Sorry, Could be some version issue. Installed imageio separately it worked.

**Comment by vladfi1** [comment]
I am also getting this, with both python2.7 and python3.4.
