### ISSUE TITLE
ffmpeg read_infos bug

### ISSUE THREAD

**Issue by fkohlgrueber** [imageio/imageio#235]
Hi,

I just found a bug in the ffmpeg plugin that results in the following traceback:
```python
Traceback (most recent call last):
  File "C:/Users/Felix/PycharmProjects/imageio/test.py", line 9, in <module>
    vid = imageio.get_reader(filename, 'ffmpeg', ffmpeg_params=['-loglevel', 'fatal', '-err_detect', 'aggressive'])
  File "C:\Users\Felix\PycharmProjects\imageio\imageio\core\functions.py", line 111, in get_reader
    return format.get_reader(request)
  File "C:\Users\Felix\PycharmProjects\imageio\imageio\core\format.py", line 169, in get_reader
    return self.Reader(self, request)
  File "C:\Users\Felix\PycharmProjects\imageio\imageio\core\format.py", line 218, in __init__
    self._open(**self.request.kwargs.copy())
  File "C:\Users\Felix\PycharmProjects\imageio\imageio\plugins\ffmpeg.py", line 306, in _open
    self._load_infos()
  File "C:\Users\Felix\PycharmProjects\imageio\imageio\plugins\ffmpeg.py", line 445, in _load_infos
    self._terminate()
  File "C:\Users\Felix\PycharmProjects\imageio\imageio\plugins\ffmpeg.py", line 430, in _terminate
    if self._frame_catcher:
AttributeError: 'Reader' object has no attribute '_frame_catcher'
```

This happens if the ffmpeg process doesn't print anything to stderr. The problem is that `self._frame_catcher` is initialized after the call to `self._load_infos` which in case of an error calls `self._terminate` which then accesses `self._frame_catcher`.

You can reproduce the bug by using the code changes from #234 and passing `ffmpeg_params=['-loglevel', 'fatal']` to the reader.

Here's the relevant section of the ffmpeg reader (Line 305...):
```python
...
# Start ffmpeg subprocess and get meta information
self._initialize()
self._load_infos()  # accesses self._frame_catcher in case of an error

# For cameras, create thread that keeps reading the images
self._frame_catcher = None
...
```

**Comment by almarklein** [comment]
Good catch! I think a good fix would be to initialize the `__frame_catcher` attribute.  E.g at the top of the Reader class:
```py
class Reader(Format.Reader):
    _exe = None
    _frame_catcher = None
```

Do you mind writing a PR for this?
