### ISSUE TITLE
ffmpeg not being downloaded

### ISSUE THREAD

**Issue by kartikarora** [imageio/imageio#240]
Until two days ago, imageio was downloading ffmpeg correctly. It is not doing so anymore.
```
ERR Traceback (most recent call last):
ERR   File "restapi.py", line 9, in <module>
ERR     from modules.location_from_media_module import location_from_media
ERR     from helpers.flicksys_audio_video import get_video, get_frame, make_url, delete_file
ERR   File "/home/vcap/app/helpers/flicksys_audio_video.py", line 5, in <module>
ERR   File "/app/.heroku/python/lib/python2.7/site-packages/moviepy/editor.py", line 22, in <module>
ERR     from .video.io.VideoFileClip import VideoFileClip
File "/app/.heroku/python/lib/python2.7/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
ERR     from moviepy.video.VideoClip import VideoClip
ERR   File "/app/.heroku/python/lib/python2.7/site-packages/moviepy/video/VideoClip.py", line 20, in <module>
ERR     from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
ERR   File "/app/.heroku/python/lib/python2.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 19, in <module>
ERR   File "/app/.heroku/python/lib/python2.7/site-packages/moviepy/config.py", line 38, in <module>
ERR     FFMPEG_BINARY = get_exe()
ERR   File "/app/.heroku/python/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 86, in get_exe
ERR     raise NeedDownloadError('Need ffmpeg exe. '
ERR imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download it by calling:
ERR   imageio.plugins.ffmpeg.download()
```

Details of deployed server:

IBM Bluemix CloudFoundry App
Runs Ubuntu 14.04 LTS Server
imageio installed by Moviepy as dependency. Moviepy installed via pip.

Adding the line `imagio.plugins.ffmpeg.download()` to my python code has no effect. Also, I'm not sure why it is looking for ffmpeg exe when it is running on a linux server.

**Comment by kartikarora** [comment]
Fixed in Zulko/moviepy#493
