### ISSUE TITLE
Cannot read PNG image

### ISSUE THREAD

**Issue by alexforencich** [imageio/imageio#246]
When I attempt to read in a PNG image, I get the following exception:

    Traceback (most recent call last):
      File "./wavegif.py", line 12, in <module>
        frames.append((imageio.imread("frame0.png"), 12))
      File "/usr/lib/python3.6/site-packages/imageio/core/functions.py", line 187, in imread
        return reader.get_data(0)
      File "/usr/lib/python3.6/site-packages/imageio/core/format.py", line 341, in get_data
        im, meta = self._get_data(index, **kwargs)
      File "/usr/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 208, in _get_data
        im, info = PillowFormat.Reader._get_data(self, index)
      File "/usr/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 116, in _get_data
        im = pil_get_frame(self._im, self._grayscale)
      File "/usr/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 419, in pil_get_frame
        p.shape = -1, len(im.palette.mode)
    ValueError: cannot reshape array of size 21 into shape (4)

Running python 3.6.0, pillow 4.1.0, imageio 2.1.2.

**Comment by almarklein** [comment]
Same answer as in #245 :)

**Comment by alexforencich** [comment]
Image in question:

![frame0](https://cloud.githubusercontent.com/assets/508807/24977223/30713fe0-1f81-11e7-9495-32ab1704f10f.png)

**Comment by almarklein** [comment]
I am able to reproduce this. It seems to be related to the image having an RGB palette, but Pillow's `im.palette.mode` reporting RGBA.

**Comment by almarklein** [comment]
See also #210, but there we had an image with a palette of 256 elements, so we could detect the situation. With smaller palettes we this gets ambiguous; I could solve it for this use-case, but it would apply a wrong palette for RGB paletes that do have a size divisible by 4. In other words, we need a better fix.

**Comment by almarklein** [comment]
Thanks for reporting this!

Could I use that image in the test suite to prevent regressions?

**Comment by alexforencich** [comment]
That's probably fine; it was extracted from a gif from http://cultofthepartyparrot.com/ with imagemagick.
