### ISSUE TITLE
SSL Certificate error downloading ffmpeg on mac (switch to requests?)

### ISSUE THREAD

**Issue by peircej** [imageio/imageio#318]
Hi there, 

I'm getting the following errors trying to download ffmpeg on a mac (10.13.3) with Python3.6 or Python2.7. I'm pretty sure the issue here is that the packaged urllib is useless on the mac! It has long been known that it fails to find the right certificates and this has just recently affected the ffmpeg download from imageio (I imagine a certificate has recently changed at github?)

Anyway, the long and short of it is that this can be fixed by `pip install requests[security]` and then
```
import requests

url = "https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-osx-v3.3.1"
response = requests.get(url)
if response.status_code == 200:
    with open(download_location, 'wb') as f:
        f.write(response.content)
```

It isn't quite as simple as `urlopen()` and it means a new dependency but then much more robust downloading (for mac users). I guess you could make things more ugly by using `urlopen()` on win/linux and only use requests on OSX. 

thoughts?

## Errors:
Python 3.6:
```
>>> from urllib.request import urlopen 
>>> url = 'https://github.com/imageio/imageio-binaries/tree/master/ffmpeg/ffmpeg-osx-v3.3.1'
>>> a = urlopen(url)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)
```

Python2.7:
```
>>> from urllib import urlopen
>>> url = 'https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-osx-v3.3.1'
>>> urlopen(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)
```

**Comment by peircej** [comment]
I didn't make it explicit but it was probably obvious that I meant this as potential replacement code for `core.util.urlopen`

**Comment by almarklein** [comment]
I am hesitant to pull in another dependency (or 5, if you also count requests' deps). How'd you feel about making requests an optional dependency? I.e. use requests when available, use urllib otherwise.

Not sure if we can reliably catch this kind of certificate error to provide a "plz install requests" error message, but we could document somewhere in the docs related to the download functions.

**Comment by peircej** [comment]
Yes, I hear you. I have the same issue in PsychoPy trying to minimize the insane requirements list. Actually I've just discovered another way of doing this that only requires `certifi.where()` and I'm just testing that. 
The idea of trapping the error and then trying an alternative method is going to make your urlopen function a bit uglier, but that is the kindest solution for the poor unsuspecting user! 
I'm happy to provide a PR if that's what you're happy with. Wanted to check first

**Comment by almarklein** [comment]
That sounds better.

> I'm happy to provide a PR if that's what you're happy with. 

Better still :)

**Comment by scivision** [comment]
Just saw that Pip 9.0.2 had this release note:  Fallback to using SecureTransport on macOS when the linked OpenSSL is too old  to support TLSv1.2.

wonder if something analogous is going on here.

**Comment by almarklein** [comment]
@scivision  Interesting, though my understanding of SSL/Certs is too limited to tell whether it's related...

**Comment by Schrodinger1926** [comment]
Immediate **hack**

`cd /Users/sidharth/Library/Application\ Support/imageio`
`mkdir ffmpeg`
`cd ffmpeg`
`wget https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-osx-v3.2.4`

NOTE: do NOT supply any path to directory argument of `imageio.plugins.ffmeg.download(directory = None)`

**Comment by ferreirafabio** [comment]
I was able to solve this issue manually. Maybe the following information helps the developers solving the the problem:

1. manually download the built (this is where the SSL error occurs): https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-osx-v3.2.4
2. paste the file to the path: /Users/yourusername/Library/Application\ Support/imageio/ffmpeg/
3. re-run the code


**what didn't help in my case:**
- upgrading moviepy with pip, then prompting the ffmpeg download through importing movie.editor
- importing imageio and executing imageio.plugins.ffmpeg.download()
- brew install ffmpeg

see also: https://stackoverflow.com/questions/45467234/ffmpeg-installation-on-macos-for-moviepy-fails-with-ssl-error

**Comment by RaphP** [comment]
Hello,
I had the same problem on my Mac and solved it by using the command in terminal : 
`/Applications/Python\ 3.6/Install\ Certificates.command`

I found the solution on [https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error](url)

**Comment by almarklein** [comment]
Closing this. With #425 the ffmpeg binary is no longer downloaded in this way. Instead the user needs to install `imageio-ffmpeg` which includes the exe in the platform specific wheels (hooray wheels!).

**Comment by meerak389** [comment]
> /Applications/Python\ 3.6/Install\ Certificates.command

Thanks it worked for me too
