### ISSUE TITLE
Singleton image; can only append image data once.

### ISSUE THREAD

**Issue by henfri** [imageio/imageio#368]
Hello,

thanks for writing imageio!
I have a Problem writing an animated gif though:
```

for filename in ll:
    images.append(imageio.imread(join(p,filename)))
imageio.mimsave(join(p,'movie144.gif'), images,format='GIF') 
```

I get this error:
```
Traceback (most recent call last):
  File "[...]\eclipse\plugins\org.python.pydev_3.9.2.201502050007\pysrc\pydevd.py", line 2235, in <module>
    globals = debugger.run(setup['file'], None, None)
  File "[...]\eclipse\plugins\org.python.pydev_3.9.2.201502050007\pysrc\pydevd.py", line 1661, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\wilco_models\ShortRange_Sector_Model\postprocessing\gif.py", line 22, in <module>
    imageio.mimsave(join(p,'movie144.gif'), images,format='GIF') 
  File "[...]\pythonxy\python27\lib\site-packages\imageio\functions.py", line 303, in mimsave
    writer.append_data(im)
  File "[...]\pythonxy\python27\lib\site-packages\imageio\base.py", line 479, in append_data
    return self._append_data(im, total_meta)
  File "[...]\pythonxy\python27\lib\site-packages\imageio\plugins\plugin_freeimage.py", line 97, in _append_data
    raise RuntimeError('Singleton image; can only append image data once.')
RuntimeError: Singleton image; can only append image data once.
```

What am I doing wrong here?

Regards,
Hendrik

**Comment by almarklein** [comment]
I think it tries to write as a non-animated gif. Try omitting the `format` argument.

**Comment by almarklein** [comment]
I tried to reproduce (on py3 and p2) using:
```py
import imageio

im = imageio.imread("imageio:chelsea.png")
ims = [im, im*0.5, im * 0.1]

imageio.mimsave('movie144.gif', ims, format='GIF')
```

But it works fine. Maybe this was on an older version of imageio and whatever the issue was, it has been fixed ... closing!

@henfri if you still see the issue with the latest version of imageio, please reopen.
