### ISSUE TITLE
search_read_format() incorrectly returns Tiff-Pillow reader for raw formats

### ISSUE THREAD

**Issue by xkortex** [imageio/imageio#459]
imageio==2.5.0
Pillow==6.0.0
OS == various ubuntu 16/18.04
python == 2.7, 3.6

I'm processing various raw formats, namely: arw, cr2, dng, nef, raf.

For all but .raf, I find search_read_format() returns a `<Format TIFF-PIL - TIFF format (Pillow)>`. .raf returns None (expected). The nef files can successfully be loaded, as can some of the dng files, but the rest give various errors on imread. For example:

The output of can_read returns true. 

```ipython
In [30]: uri = fns_dng[1]
    ...: fmtr = search_read_format(uri)
    ...: req = imageio.core.request.Request(uri, 'r?')
    ...: print(type(fmtr))
    ...: print(fmtr.can_read(req))
    ...: 
<class 'imageio.plugins.pillowmulti.TIFFFormat'>
True
```

But `imageio.imread(uri)` fails:
```
Traceback (most recent call last):

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-21-b516a1603f2a>", line 1, in <module>
    imageio.imread(fns_dng[1])

  File "/home/ubuntu/.virtualenvs/medifor3/lib/python3.6/site-packages/imageio/core/functions.py", line 221, in imread
    reader = read(uri, format, "i", **kwargs)

  File "/home/ubuntu/.virtualenvs/medifor3/lib/python3.6/site-packages/imageio/core/functions.py", line 143, in get_reader
    return format.get_reader(request)

  File "/home/ubuntu/.virtualenvs/medifor3/lib/python3.6/site-packages/imageio/core/format.py", line 164, in get_reader
    return self.Reader(self, request)

  File "/home/ubuntu/.virtualenvs/medifor3/lib/python3.6/site-packages/imageio/core/format.py", line 214, in __init__
    self._open(**self.request.kwargs.copy())

  File "/home/ubuntu/.virtualenvs/medifor3/lib/python3.6/site-packages/imageio/plugins/pillow.py", line 127, in _open
    self._im = factory(self._fp, "")

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/PIL/ImageFile.py", line 102, in __init__
    self._open()

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py", line 950, in _open
    self._seek(0)

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py", line 1017, in _seek
    self._setup()

  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/PIL/TiffImagePlugin.py", line 1200, in _setup
    raise SyntaxError("unknown pixel mode")

  File "<string>", line unknown
SyntaxError: unknown pixel mode
```

Unfortunately I cannot share any of the files I am testing on at the current time, but I wanted to get the bug report out before I forgot.

**Comment by almarklein** [comment]
Do you happen to know what format *should* be used instead?

**Comment by FirefoxMetzger** [comment]
@xkortex If you still have the images in question? If so could you test with a recent version of ImageIO and see if the issue still exists?

Based on what you have written, it looks like the Pillow backend is being used, whereas it should really use the FreeImage backend. All the formats you mentioned should (according to our docs) be read by FreeImage (via `format="RAW-FI"`). I double-checked our (current) source code, and - indeed - the only backend registered for those extensions is FreeImage.

> The nef files can successfully be loaded, as can some of the dng files

That's interesting. Likely FreeImage was correctly selected here, but I will double-check if pillow has support for these. If so, we can add those as formats supported by the backend.

**Comment by FirefoxMetzger** [comment]
Closing this due to lack of activity, and because it is likely fixed by one of the recent changes to how formats are resolved (although I can't test this, because I don't have the images in question).

If this issue persists or if there is more to discuss, feel free to comment and I will reopen.
