### ISSUE TITLE
creation of ~/.imageio is not threadsafe

### ISSUE THREAD

**Issue by christopherhesse** [imageio/imageio#460]
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "segfault.py", line 11, in make_iterator
    r = imageio.get_reader(uri="imageio:cockatoo.mp4", format="ffmpeg")
  File "/opt/conda/lib/python3.7/site-packages/imageio/core/functions.py", line 130, in get_reader
    request = Request(uri, "r" + mode, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/imageio/core/request.py", line 126, in __init__
    self._parse_uri(uri)
  File "/opt/conda/lib/python3.7/site-packages/imageio/core/request.py", line 154, in _parse_uri
    self._filename = get_remote_file("images/" + fn, auto=True)
  File "/opt/conda/lib/python3.7/site-packages/imageio/core/fetching.py", line 69, in get_remote_file
    directory = given_directory or appdata_dir("imageio")
  File "/opt/conda/lib/python3.7/site-packages/imageio/core/util.py", line 487, in appdata_dir
    os.mkdir(path)
FileExistsError: [Errno 17] File exists: '/root/.imageio'
```

Probably this could use `os.makedirs(path, exist_ok=True)`

**Comment by almarklein** [comment]
Nice catch! Should be easy enough to fix indeed.

**Comment by sciunto** [comment]
note that it is not a good idea to store config files in /home/$USER/, but rather to follow the  XDG Base Directory Specification. See comments in https://stackoverflow.com/questions/1024114/location-of-ini-config-files-in-linux-unix for instance.

**Comment by almarklein** [comment]
@sciunto A PR to change this about [here](https://github.com/imageio/imageio/blob/master/imageio/core/util.py#L431) would be very welcome :D

**Comment by sciunto** [comment]
Thanks for pointing the right place. I'll open an issue to keep track of it. I'll try to improve it although I do not promise a PR very soon
.
