### ISSUE TITLE
Exception raised on macOs - Azure builds when trying to download "libfreeimage-3.16.0-osx10.6.dylib".

### ISSUE THREAD

**Issue by KelSolaar** [imageio/imageio#461]
Hi,

I'm experiencing some failed builds when `imagio` tries to pull `libfreeimage-3.16.0-osx10.6.dylib` on macOs:

```python
Imageio: 'libfreeimage-3.16.0-osx10.6.dylib' was not found on your computer; downloading it now.
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>.
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>.
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>.
Error while fetching file: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)>.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/vsts/.conda/envs/colour_env/lib/python2.7/site-packages/imageio/plugins/_freeimage.py", line 70, in download
    get_remote_file(fname=fname, directory=directory, force_download=force_download)
  File "/Users/vsts/.conda/envs/colour_env/lib/python2.7/site-packages/imageio/core/fetching.py", line 130, in get_remote_file
    _fetch_file(url, filename)
  File "/Users/vsts/.conda/envs/colour_env/lib/python2.7/site-packages/imageio/core/fetching.py", line 189, in _fetch_file
    % os.path.basename(file_name)
IOError: Unable to download 'libfreeimage-3.16.0-osx10.6.dylib'. Perhaps there is a no internet connection? If there is, please report this problem.
```

https://dev.azure.com/colour-science/Colour/_build/results?buildId=269&view=logs

I'm not exactly sure on what is happening here thus ideas are welcomed!

Cheers,

Thomas

**Comment by almarklein** [comment]
I'm not export on this, but perhaps your build machine does not know about the (new?) certificates used by Github? What kind of machine are you building on, and can you update it?

**Comment by KelSolaar** [comment]
Hi @almarklein,

So this is a Microsoft Azure macOs VM thus I'm not sure about the certificate.

The macOs config is like that, maybe something will jump out to you:

```
- job: 'Test_macOS'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
    maxParallel: 3
  pool:
    vmImage: 'xcode9-macos10.13'
  steps:
  - script: |
      sudo chmod -R 777 /usr/local/miniconda/envs
    displayName: 'Fix for conda error on macOS'
  - task: CondaEnvironment@1
    inputs:
      createCustomEnvironment: true
      environmentName: 'colour_env'
      packageSpecs: 'python=$(python.version)'
      installOptions: -y
  - script: |
      conda activate colour_env
      conda install -y imageio matplotlib numpy scipy
      conda install -y pyqt
      conda install -y nose six coveralls flake8 mock==1.0.1
      python -c "import imageio;imageio.plugins.freeimage.download()"
    displayName: 'Install dependencies'
  - script: flake8 colour
    displayName: 'flake8'
  - script: nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS --with-coverage --cover-package=colour --with-xunit colour
    displayName: 'nosetest'
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/nosetests.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()
```

**Comment by almarklein** [comment]
> maybe something will jump out to you

No, not really :)  The only thing I can think of is that you add a line to script that update the os's certificates.

**Comment by KelSolaar** [comment]
I kind of fixed it by not using Conda on macOs but pip, kind of a shame but it does work. I will close this one to tidy up things.

**Comment by KelSolaar** [comment]
Hi,

So the same started to happen on Travis-CI now: https://travis-ci.org/colour-science/colour/jobs/573016745

It seems like there is _some_ certificate expiring, still unclear what.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
I managed to reproduce it with a minimal reproducible test, this seems to be happening with anything trying to download a resource online with Conda on Python 2.7: https://travis-ci.com/KelSolaar/CertificateRamblings/builds/123584704

**Comment by KelSolaar** [comment]
Closing again as it is unrelated to `imageio`.

**Comment by almarklein** [comment]
Nice work tracing the issue down. Hopefully it can be fixed at conda.

**Comment by KelSolaar** [comment]
Yeah hopefully :) The first dev over there was trigger happy closing the issue, we will see...

**Comment by KelSolaar** [comment]
Looks like it is fixed! 🍾
