### ISSUE TITLE
imread ver 2.6.1 fails on this geotiff file with err=-2

### ISSUE THREAD

**Issue by sound-fx** [imageio/imageio#520]
The code

```
import imageio
land_sea_map = imageio.imread('lsm.geotiff')
```
works as expected using Python 2.7.16 and imageio 2.5.0 on Windows 10 (all from the default install of 64-bit Anaconda Distribution 2010.10), with [this lsm.geotiff file](https://github.com/hfs/land-sea-mask/raw/master/lsm.geotiff).

But when using Python 3.7.6 and imageio 2.6.1 on Windows 10 (all coming from the default install of the 64-bit Anaconda Individual Edition 2020.02), the same code gives error "-2", as seen in the traceback below:

```
In [1]: import imageio

In [2]: imageio.imread('lsm.geotiff')
Traceback (most recent call last):

  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\lib\site-packages\imageio\plugins\pillow.py", line 671, in pil_try_read
    im.getdata()[0]

  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\lib\site-packages\PIL\Image.py", line 1249, in getdata
    self.load()

  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\lib\site-packages\PIL\TiffImagePlugin.py", line 1070, in load
    return self._load_libtiff()

  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\lib\site-packages\PIL\TiffImagePlugin.py", line 1182, in _load_libtiff
    raise OSError(err)

OSError: -2


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-2-4214415aae08>", line 1, in <module>
    imageio.imread('LandSeaMap_0p1DegResolution_lsm.geotiff')

  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\lib\site-packages\imageio\core\functions.py", line 264, in imread
    reader = read(uri, format, "i", **kwargs)

  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\lib\site-packages\imageio\core\functions.py", line 186, in get_reader
    return format.get_reader(request)

  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\lib\site-packages\imageio\core\format.py", line 164, in get_reader
    return self.Reader(self, request)

  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\lib\site-packages\imageio\core\format.py", line 214, in __init__
    self._open(**self.request.kwargs.copy())

  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\lib\site-packages\imageio\plugins\pillow.py", line 137, in _open
    pil_try_read(self._im)

  File "C:\Users\greg\AppData\Local\Continuum\anaconda3-64\lib\site-packages\imageio\plugins\pillow.py", line 682, in pil_try_read
    raise ValueError(error_message)

ValueError: Could not load "" 
Reason: "-2"
Please see documentation at: http://pillow.readthedocs.io/en/latest/installation.html#external-libraries


In [3]: 
```

**Comment by kmilos** [comment]
This is a known `libtiff` issue, see https://github.com/python-pillow/Pillow/issues/4237

Either downgrade to libitiff 4.0.10 temporarily, or use the `TIFF-FI` backend of imageio.
