### ISSUE TITLE
Cannot imwrite into a directory named *.zip

### ISSUE THREAD

**Issue by azymohliad** [imageio/imageio#548]
When I try to save the image into a directory which name ends with `.zip` it fails, assuming it should be a zip archive. For example:
```
imageio.imwrite('test.zip/test.jpg', img)
```
where `test.zip` is an existing directory, it fails with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/azymohliad/.local/lib/python3.8/site-packages/imageio/core/functions.py", line 305, in imwrite
    writer.append_data(im)
  File "/home/azymohliad/.local/lib/python3.8/site-packages/imageio/core/format.py", line 244, in __exit__
    self.close()
  File "/home/azymohliad/.local/lib/python3.8/site-packages/imageio/core/format.py", line 261, in close
    self.request.finish()
  File "/home/azymohliad/.local/lib/python3.8/site-packages/imageio/core/request.py", line 404, in finish
    zf = zipfile.ZipFile(self._filename_zip[0], "a")
  File "/usr/lib/python3.8/zipfile.py", line 1251, in __init__
    self.fp = io.open(file, filemode)
IsADirectoryError: [Errno 21] Is a directory: '/home/azymohliad/Downloads/test.zip'
```
Would it be a good idea to additionally check if it's a regular file whenever .zip extension is detected in the path before feeding it to `zipfile`?

For now I can work this around by:
```
imageio.imwrite(open('test.zip/test.jpg', 'wb'), img, format='JPEG-PIL')
```

**Comment by almarklein** [comment]
Why do you have a directory name ending in ".zip"? :P

> Would it be a good idea to additionally check if it's a regular file whenever .zip extension is detected in the path before feeding it to zipfile?

Yes, good idea!

**Comment by azymohliad** [comment]
Awesome! Thanks for such a fast fix!

> Why do you have a directory name ending in ".zip"? :P

I had a script that took a list of .jpg files and for each of them created a directory for some output, named as input file without extension. It failed on files `something.zip.jpg` because it resulted in `something.zip` for output directory name.
