### ISSUE TITLE
Reading into zip files doesn't support windows-style paths

### ISSUE THREAD

**Issue by FirefoxMetzger** [imageio/imageio#618]
On Windows all of these variants work:

```python
iio.imread("./test1.zip/images/chelsea.png")
iio.imread(".\\test1.zip\\images/chelsea.png")
iio.imread(".\\test1.zip/images/chelsea.png")
```

but this:

```python
iio.imread(".\\test1.zip\\images\\chelsea.png")
iio.imread("./test1.zip\\images\\chelsea.png")
iio.imread("./test1.zip/images\\chelsea.png")
```

fails with `KeyError`.

<details>
<summary>Stacktrace</summary>

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\functions.py", line 262, in imread
    reader = read(uri, format, "i", **kwargs)
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\functions.py", line 177, in get_reader
    format = formats.search_read_format(request)
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\format.py", line 682, in search_read_format
    if format.can_read(request):
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\format.py", line 184, in can_read
    return self._can_read(request)
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\plugins\pillow.py", line 109, in _can_read
    if request.firstbytes:
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\request.py", line 492, in firstbytes
    self._read_first_bytes()
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\request.py", line 501, in _read_first_bytes
    f = self.get_file()
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\request.py", line 395, in get_file
    self._file = self._zipfile.open(name, "r")
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python38\lib\zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'images\\\\chelsea.png' in the archive"
```

</details>

Essentially, windows-style paths inside the zip-file portion of the file don't work. My preferred way of resolving this is to migrate to using `pathlib.Path` objects to describe the paths. This will take care of any OS differences (and more).

---

On the same token, I'd like to advocate using `"./test1.zip#images/chelsea.png"` over `./test1.zip/images/chelsea.png`, i.e., use `#` instead of `/` as separator. This would make `images/chelsea.png` a fragment of the path `./test1.zip` according to the URI spec, which allows us to have the standard library (`urllib.parse`) separate the pieces for us. 

This would also catch the `/strange/folder.zip/that/is/no/zip/image.jpg` edge case and handle it properly. (Which we can't actually handle if we want to remain backwards compatible)

**Comment by FirefoxMetzger** [comment]
> This would also catch the /strange/folder.zip/that/is/no/zip/image.jpg edge case and handle it properly. 

Liking this issue here for reference: https://github.com/imageio/imageio/issues/548

**Comment by almarklein** [comment]
Although initially enthusiastic, I've never become a fan of `pathlib`. If you want to go that route, be my guest, but IMO a well-placed `normpath` should also do the trick :)  

> use `#` instead of `/` as separator

That sounds reasonable. I did some brief googling to see if there is a common way to address files inside a zipfile, but there does not seem to be any. 

> This would also catch the `/strange/folder.zip/that/is/no/zip/image.jpg` edge case and handle it properly. (Which we can't actually handle if we want to remain backwards compatible)

We can though, right? We already detect whether the `something.zip` is actually a directory.

Anyway, unless we want to introduce a subtle (and therefore potentially really anoying) backwards incompatibility, the only advantage is the clearer URI from the user's perspective. (Which could still be worth it.)

**Comment by FirefoxMetzger** [comment]
> IMO a well-placed normpath should also do the trick :)

Yep, it would. I'm just a lazy person that likes to be pampered, so if I can do `.suffix`, `.parent[1]`, `.name` without worrying about OS-specific quirks and weird paths users may come up with, I'll choose the easy way 😄 

> I did some brief googling to see if there is a common way to address files inside a zipfile

I haven't really seen another library with this feature, so I would be surprised if there is an actual standard.

> We can though, right?

Yes, we do, though this is expensive as we have to make an OS/filesystem call for every `.zip` that occurs in the path to see if it is a directory or a file which might be slow if we do it a lot. This works but is somewhat of a hack/workaround that lives sub-surface (and is hence invisible to the user).

I'm actually not sure anymore why I was thinking we can't be backwards compatible with this. We can keep the check for `some.zip/` for a while and convert it to `some.zip#` if it was a zip file before processing the request.

`#` would mainly make our life easier (on top of being cleaner for the end-user).

**Comment by almarklein** [comment]
right, we can also deprecate the older use over time, so eventually the codebase would be cleaner too.
