### ISSUE TITLE
imageio.imwrite no longer works with io.BytesIO

### ISSUE THREAD

**Issue by ugtony** [imageio/imageio#687]
Hi, 
The code below works well imageio==2.10.4 while doesn't work with imageio==2.11.0, 
please take a look, thanks.
```
import io
import imageio
import numpy as np

image = np.zeros((200,200))
bytes_io = io.BytesIO()
imageio.imwrite(bytes_io, image, 'jpeg')
```

error message
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/imageio/core/imopen.py", line 149, in imopen
    return config.plugin_class(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/imageio/config/plugins.py", line 108, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/usr/local/lib/python3.8/dist-packages/imageio/core/legacy_plugin_wrapper.py", line 68, in __init__
    raise InitializationError(
imageio.core.request.InitializationError: `JPEG-FI` can not write to `<_io.BytesIO object at 0x7f100f74f270>`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/imageio/core/functions.py", line 195, in imwrite
    with imopen(uri, "wi", plugin=format) as file:
  File "/usr/local/lib/python3.8/dist-packages/imageio/core/imopen.py", line 167, in imopen
    raise err_type(err_msg) from err_from
RuntimeError: `jpeg` can not handle the given uri.
```

**Comment by FirefoxMetzger** [comment]
That reproduces for me on master. Looks like an omission in the new fast-path for file extensions. The following workaround (using the v3 API) appears to work fine:

```python
import io
import imageio
import numpy as np

image = np.zeros((200,200))
bytes_io = io.BytesIO()

# explicitly set the backend to use and mode to write in
iio.v3.imwrite(bytes_io, image, plugin="pillow", format="jpeg", mode="L")
```

I will have a look into where legacy imwrite breaks soon™ (hopefully this afternoon). It sounds like it should be a small fix, in which case we should be able to release it this week.
