### ISSUE TITLE
Support for FreeBSD OS ?

### ISSUE THREAD

**Issue by Zulko** [imageio/imageio#76]
Hey ! I got this message on Reddit, do you think supporting FreeBSD would be possible ?

 have a beefy FreeNAS server and have a ffmpeg jail setup to do some video editing and image processing.

Right now I'm using Make to edit movies (yes, GNU Make). I'd like to use moviepy however it doesn't look like it is supported:

```
FNAME_PER_PLATFORM = {
'osx32': 'libfreeimage-3.16.0-osx10.6.dylib',  # universal library
'osx64': 'libfreeimage-3.16.0-osx10.6.dylib',
'win32': 'FreeImage-3.15.4-win32.dll',
'win64': 'FreeImage-3.15.1-win64.dll',
'linux32': 'libfreeimage-3.16.0-linux32.so',
'linux64': 'libfreeimage-3.16.0-linux64.so',
}
```

distutils.util.get_platform() returns:

```
>>> get_platform()
'freebsd-9.3-RELEASE-p8-amd64'
```

**Comment by almarklein** [comment]
We should at least allow using ffmpeg using the system executable.

**Comment by almarklein** [comment]
Actually, when the platform is not supported, imageio will fallback to the system `ffmpeg` executable. Isn't that enough? Alternatively, we should wrap up that PR of yours that allows setting the ffmpeg executable.

**Comment by almarklein** [comment]
If just `ffmpeg` does not work. The user can now do `os.environ['IMAGEIO_FFMPEG_EXE'] = '/path/to/my/ffmpeg'.

**Comment by Zulko** [comment]
Very cool, thanks.

**Comment by jedediahfrey** [comment]
I'm using PC-BSD and decided to give this a try.

It still fails on the init of imagio since it is directly referencing a dictionary from get_platform().

	Traceback (most recent call last):
	  File "myFirstMovie.py", line 2, in <module>
		import moviepy.editor as mpy
	  File "/usr/local/lib/python3.4/site-packages/moviepy/editor.py", line 22, in <module>
		from .video.io.VideoFileClip import VideoFileClip
	  File "/usr/local/lib/python3.4/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
		from moviepy.video.VideoClip import VideoClip
	  File "/usr/local/lib/python3.4/site-packages/moviepy/video/VideoClip.py", line 17, in <module>
		from imageio import imread
	  File "/usr/local/lib/python3.4/site-packages/imageio-1.2-py3.4.egg/imageio/__init__.py", line 36, in <module>
		from . import plugins  # noqa
	  File "/usr/local/lib/python3.4/site-packages/imageio-1.2-py3.4.egg/imageio/plugins/__init__.py", line 81, in <module>
		from . import freeimage  # noqa
	  File "/usr/local/lib/python3.4/site-packages/imageio-1.2-py3.4.egg/imageio/plugins/freeimage.py", line 17, in <module>
		from ._freeimage import fi, IO_FLAGS, FNAME_PER_PLATFORM  # noqa
	  File "/usr/local/lib/python3.4/site-packages/imageio-1.2-py3.4.egg/imageio/plugins/_freeimage.py", line 1261, in <module>
		fi = Freeimage()
	  File "/usr/local/lib/python3.4/site-packages/imageio-1.2-py3.4.egg/imageio/plugins/_freeimage.py", line 404, in __init__
		self._load_freeimage()
	  File "/usr/local/lib/python3.4/site-packages/imageio-1.2-py3.4.egg/imageio/plugins/_freeimage.py", line 428, in _load_freeimage
		fname = FNAME_PER_PLATFORM[get_platform()]
	KeyError: None

I haven't yet gotten my BSD machine up to being a dev environment yet but I can take a look at it in a few days. (Once I re-install FreeBSD11-CURRENT)

**Comment by almarklein** [comment]
@jedediahfrey Thanks for testing! I'll make some changes to deal more flexible with "exotic" platforms :)

**Comment by almarklein** [comment]
Fixed it. Could you please try the latest master?

**Comment by almarklein** [comment]
I am assuming that this works. Please reopen if this is not the case.
