### ISSUE TITLE
Reading bytes with ffmpeg broken in 2.11.0

### ISSUE THREAD

**Issue by daveisfera** [imageio/imageio#777]
Starting with 2.11.0, reading from `bytes` using `ffmpeg` breaks with the following error:
```
Traceback (most recent call last):
  File "/Users/dlj/projects/imageio_test/venv/lib/python3.9/site-packages/imageio/core/imopen.py", line 149, in imopen
    return config.plugin_class(request, **kwargs)
  File "/Users/dlj/projects/imageio_test/venv/lib/python3.9/site-packages/imageio/config/plugins.py", line 108, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/Users/dlj/projects/imageio_test/venv/lib/python3.9/site-packages/imageio/core/legacy_plugin_wrapper.py", line 63, in __init__
    raise InitializationError(
imageio.core.request.InitializationError: `FFMPEG` can not read `<_io.BytesIO object at 0x10e4ed950>`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/dlj/projects/imageio_test/test.py", line 106, in <module>
    run()
  File "/Users/dlj/projects/imageio_test/test.py", line 89, in run
    reader = imageio.get_reader(io.BytesIO(chunk), "ffmpeg")
  File "/Users/dlj/projects/imageio_test/venv/lib/python3.9/site-packages/imageio/core/functions.py", line 98, in get_reader
    image_file = imopen(uri, "r" + mode, plugin=format)
  File "/Users/dlj/projects/imageio_test/venv/lib/python3.9/site-packages/imageio/core/imopen.py", line 167, in imopen
    raise err_type(err_msg) from err_from
RuntimeError: `ffmpeg` can not handle the given uri.
```

**Comment by FirefoxMetzger** [comment]
This is a known issue and currently tracked in https://github.com/imageio/imageio/issues/686. As of v2.15 you can use the `format_hint` kwarg of the v3 API as a workaround:

```python
import imageio as iio
import io

frame = iio.v3.imread(video_bytes, format_hint=".mp4")
frame = iio.v3.imread(io.BytesIO(video_bytes), format_hint=".mp4")
```

and more details are given in the other issue.

I will close this issue in favor of #686 , but if misunderstand the problem then feel free to comment and I will reopen.
