### ISSUE TITLE
Cannot open BMP file with Pillow backend

### ISSUE THREAD

**Issue by bw7715** [imageio/imageio#797]
When I try read .bmp file I get an error:

```python
Traceback (most recent call last):
  File "E:\Work\project\dataset.py", line 67, in _load_image
    img = imageio.imread(img_path)
  File "E:\Work\Venvs\p39\lib\site-packages\imageio\__init__.py", line 86, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "E:\Work\Venvs\p39\lib\site-packages\imageio\v2.py", line 159, in imread
    with imopen(uri, "ri", plugin=format) as file:
  File "E:\Work\Venvs\p39\lib\site-packages\imageio\core\imopen.py", line 333, in imopen
    raise err_type(err_msg)
ValueError: Could not find a backend to open `D:\Tests\samples\train\images\1.bmp`` with iomode `ri`.

Process finished with exit code 1
```

Try on:
Python 3.9 and 3.10
imageio 2.17.0
Pillow 9.1.0

**Comment by FirefoxMetzger** [comment]
Interesting. Do you happen to have an example image and/or a snippet of code that reproduces the issue? When i try to open a BMP it works just fine:

```python
>>> import imageio.v3 as iio
>>> img = iio.imread("imageio:chelsea.png")
>>> iio.imwrite("test.bmp", img)
>>> img2 = iio.imread("test.bmp")
>>> all(img.ravel() == img2.ravel())
True
```

**Comment by bw7715** [comment]
The example works for me.

The file "D:\Tests\samples\train\images\1.bmp" was created in Windows 10 (rigth-click -> New -> Bitmap image).

But with normal .bmp file works.

Thanks.

**Comment by FirefoxMetzger** [comment]
> The file "D:\Tests\samples\train\images\1.bmp" was created in Windows 10 (rigth-click -> New -> Bitmap image).

In this case, it makes sense that you get an exception. The file that you create is empty, so ImageIO can't identify the file or read any content because there is nothing inside. Does that solve your problem @bw7715 ?

Also, @almarklein , do you think it would be useful to check if a file is empty when reading and raise a more descriptive error message?

**Comment by bw7715** [comment]
Thanks, my problem is solved.

**Comment by almarklein** [comment]
> do you think it would be useful to check if a file is empty when reading and raise a more descriptive error message?

My first reaction is to say no, because what about files that contain random bits. But perhaps an empty file is a relatively more common use-case, and should be easy to catch ... I will maken an issue.
