### ISSUE TITLE
Cannot read image from path in URI format

### ISSUE THREAD

**Issue by bw7715** [imageio/imageio#800]
When the path is given in URI format I get an error:

```python
Traceback (most recent call last):
  File "E:\Work\project\imread_test.py", line 4, in <module>
    img = imageio.imread(uri=uri)
  File "E:\Work\Venvs\p39\lib\site-packages\imageio\__init__.py", line 96, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "E:\Work\Venvs\p39\lib\site-packages\imageio\v2.py", line 200, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "E:\Work\Venvs\p39\lib\site-packages\imageio\core\imopen.py", line 110, in imopen
    request = Request(uri, io_mode, format_hint=format_hint)
  File "E:\Work\Venvs\p39\lib\site-packages\imageio\core\request.py", line 248, in __init__
    self._parse_uri(uri)
  File "E:\Work\Venvs\p39\lib\site-packages\imageio\core\request.py", line 388, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'E:\D:\Tests\samples\train\images\1.bmp'
```

Code to reproduce:

```python
import imageio

uri = "file:///D:/Tests/samples/train/images/1.bmp"
img = imageio.imread(uri=uri)
```

Tested on:
Python 3.9 and 3.10
imageio 2.17.0

**Comment by bw7715** [comment]
In a newer version (2.18.0) the problem still occurs.
Most likely `file:` is converted to `E:`.

**Comment by FirefoxMetzger** [comment]
The following works for me on master:

```python
>>> import imageio.v3 as iio
>>> iio.imwrite("test.png", iio.imread("imageio:chelsea.png"))
>>> im = iio.imread("test.png")
>>> im = iio.imread("file://test.png")
>>> im = iio.imread("file://C:\\Users\\Sebastian\\Documents\\Coding-Projects\\imageio\\test.png") 
>>> im = iio.imread("file://C:/Users/Sebastian/Documents/Coding-Projects/imageio/test.png")
```

and also in the v2 API:

```python
>>> import imageio.v2 as iio2
>>> im = iio2.imread("file://C:\\Users\\Sebastian\\Documents\\Coding-Projects\\imageio\\test.png") 
>>> im = iio2.imread("file://C:/Users/Sebastian/Documents/Coding-Projects/imageio/test.png")       
```

I don't have a D drive, so I can't replicate this part. @bw7715 Does it work for you on the C drive, or do you get the same error?

**Comment by FirefoxMetzger** [comment]
> please see that on Windows System we use three slashes in the file path

Indeed, with three slashes I can reproduce the issue. Looking at the trace it seems to be that our `Request` object doesn't parse the URI correctly. There are several things we are looking to improve with `Request` already (see: https://github.com/imageio/imageio/issues/798). Likely this behavior will improve once the request object has been refactored. On the same line of thinking, adding a single `/` before the path without specifying a schema breaks, too, as the result will be interpreted as a relative path:

```python
>>> import imageio as iio
>>> im = iio.imread("C:/Users/Sebastian/Documents/Coding-Projects/imageio/test.png")  
>>> im = iio.imread("/C:/Users/Sebastian/Documents/Coding-Projects/imageio/test.png") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\__init__.py", line 96, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\v2.py", line 200, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\imopen.py", line 110, in imopen
    request = Request(uri, io_mode, format_hint=format_hint)
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\request.py", line 248, in __init__
    self._parse_uri(uri)
  File "C:\Users\Sebastian\Documents\Coding-Projects\imageio\imageio\core\request.py", line 388, in _parse_uri
    raise FileNotFoundError("No such file: '%s'" % fn)
FileNotFoundError: No such file: 'C:\C:\Users\Sebastian\Documents\Coding-Projects\imageio\test.png'
```

A different point is that neither of the three `///` are necessary for it to be a URI, because there is no authority, and because an absolute path should not start with a `/` on Windows but rather with a drive letter. Indeed, this is how it works in `urlparse` (carefully observe the leading `/` in the path):

```python
>>> from urllib.parse import urlparse
>>> urlparse("file:///C:/Users/Sebastian/Documents/Coding-Projects/imageio/test.png")
ParseResult(scheme='file', netloc='', path='/C:/Users/Sebastian/Documents/Coding-Projects/imageio/test.png', params='', query='', fragment='')
>>> urlparse("file:C:/Users/Sebastian/Documents/Coding-Projects/imageio/test.png")    
ParseResult(scheme='file', netloc='', path='C:/Users/Sebastian/Documents/Coding-Projects/imageio/test.png', params='', query='', fragment='')
```

That being said, `pathlib` produces paths with `///` on Windows, so likely we want to support both options and treat `///` as one of Window's many quirks.

--- 

FYI @bw7715 If you have a `pathlib.Path` object, you can directly pass it to imread and it should just work.

```python
>>> import imageio as iio                                                             
>>> from pathlib import Path                                                          
>>> path = Path("C:/Users/Sebastian/Documents/Coding-Projects/imageio/test.png")
>>> im = iio.imread(path)
```
