### ISSUE TITLE
imageio.core.request.InitializationError: `FFMPEG` can not read `<bytes>`.

### ISSUE THREAD

**Issue by RichardErkhov** [imageio/imageio#819]
windows 10, python 3.10.4, imageio 2.19.3

```
#decrypt archive
decypted_archive = io.BytesIO()
with open(archive_name, 'rb') as f:
    length = os.path.getsize(archive_name)
    pyAesCrypt.decryptStream(f, decypted_archive, password, 64 * 1024, length)
decypted_archive.seek(0)
with zipfile.ZipFile(decypted_archive) as myzip:
    with myzip.open("video.avi") as video:
        print(type(video.read())) #<class 'bytes'>
        for frame in imageio.get_reader(video.read(), 'ffmpeg'):
            print(frame.shape)
```
gives an error
```
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\imageio\core\imopen.py", line 147, in imopen
    return loader(request, **kwargs)
  File "C:\Python310\lib\site-packages\imageio\core\imopen.py", line 135, in loader
    return config.plugin_class(request, **kwargs)
  File "C:\Python310\lib\site-packages\imageio\config\plugins.py", line 107, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "C:\Python310\lib\site-packages\imageio\core\legacy_plugin_wrapper.py", line 79, in __init__
    raise InitializationError(
imageio.core.request.InitializationError: `FFMPEG` can not read `<bytes>`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\videoarchiver\1.py", line 171, in <module>
    get_random_frame('archive.aes')
  File "G:\videoarchiver\1.py", line 89, in get_random_frame
    for frame in imageio.get_reader(video.read(), 'ffmpeg'):
  File "C:\Python310\lib\site-packages\imageio\v2.py", line 133, in get_reader
    image_file = imopen(uri, "r" + mode, **imopen_args)
  File "C:\Python310\lib\site-packages\imageio\core\imopen.py", line 165, in imopen
    raise err_type(err_msg) from err_from
RuntimeError: `FFMPEG` can not handle the given uri.
```

**Comment by RichardErkhov** [comment]
fixed using 
```
import imageio.v3 as iio
with ZipFile(decypted_archive, 'r') as myzip:
    with myzip.open("video.avi") as f:
        frames = iio.imread(f.read(), index=None, format_hint='.avi')
        for frame in frames:
            #show image
            cv2.imshow('frame', frame)
            cv2.waitKey(1)
```
