### ISSUE TITLE
ValueError: Could not find a backend to open `<_io.BytesIO object at 0x7f13aeb35630>`` with iomode `ri`

### ISSUE THREAD

**Issue by iiLearner** [imageio/imageio#821]
Hello!

I' m using imageio to generate gif/videos from a set of images, these images are closed in a zip file and stored on s3.
While what im doing works just fine locally, when using it on aws lambda function i have some issues.

I'm downloading the zip file, opening it and then appending the images to an images array to then generate gif/video from it.
Here's some code:

```py
 s3 = boto3.client('s3')
    # get the product
    images = []
    zip_obj = s3.get_object(
        Bucket=bucket, Key=key)
    buffer = BytesIO(zip_obj.get('Body').read())
    with zipfile.ZipFile(buffer, 'r') as zip_ref:
        for filename in zip_ref.namelist():
            image_bytes = io.BytesIO(zip_ref.open(filename).read())
            images.append(imageio.imread(image_bytes))

    imageio.mimsave(f'/tmp/{sku}.mp4', images, fps=fps)
    imageio.mimsave(f'/tmp/{sku}.gif', images, fps=fps)
```

While running this code on AWS Lambda im getting the following error:
`
[ERROR] ValueError: Could not find a backend to open <_io.BytesIO object at 0x7f13aeb35630> with iomode `ri`.
Traceback (most recent call last):
  File "/var/task/serverless_sdk/__init__.py", line 144, in wrapped_handler
    return user_handler(event, context)
  File "/var/task/handler.py", line 33, in main
    images.append(imageio.imread(image_buffer))
  File "/opt/python/imageio/v2.py", line 200, in imread
    with imopen(uri, "ri", **imopen_args) as file:
  File "/opt/python/imageio/core/imopen.py", line 303, in imopen
    raise err_type(err_msg)
`

Is there something I need to change? thank you.

**Comment by almarklein** [comment]
Sometimes imageio can detect the format from the bytes, but it may need some help by providing the `extension` or `format_hint` argument: https://imageio.readthedocs.io/en/stable/_autosummary/imageio.v3.imread.html#imageio.v3.imread

**Comment by iiLearner** [comment]
> Sometimes imageio can detect the format from the bytes, but it may need some help by providing the `extension` or `format_hint` argument: https://imageio.readthedocs.io/en/stable/_autosummary/imageio.v3.imread.html#imageio.v3.imread

That seems to have fixed the mentioned issue however its not throwing an error related to pillow, still only on aws lambda,
`
[ERROR] ImportError: cannot import name '_imaging' from 'PIL' (/opt/python/PIL/__init__.py)
Traceback (most recent call last):
  File "/var/task/serverless_sdk/__init__.py", line 144, in wrapped_handler
    return user_handler(event, context)
  File "/var/task/handler.py", line 31, in main
    images.append(imageio.imread(image_buffer, extension=".png"))
  File "/opt/python/imageio/v3.py", line 57, in imread
    with imopen(uri, "r", **plugin_kwargs) as img_file:
  File "/opt/python/imageio/core/imopen.py", line 213, in imopen
    plugin_instance = candidate_plugin(request, **kwargs)
  File "/opt/python/imageio/config/plugins.py", line 107, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "/opt/python/imageio/core/legacy_plugin_wrapper.py", line 78, in __init__
    if not self._format.can_read(request):
  File "/opt/python/imageio/core/format.py", line 241, in can_read
    return self._can_read(request)
  File "/opt/python/imageio/plugins/pillow_legacy.py", line 264, in _can_read
    Image = self._init_pillow()
  File "/opt/python/imageio/plugins/pillow_legacy.py", line 250, in _init_pillow
    from PIL import Image
  File "/opt/python/PIL/Image.py", line 132, in <module>
    from . import _imaging as core
`
