### ISSUE TITLE
Confusing error message when trying to imwrite a boolean array

### ISSUE THREAD

**Issue by anntzer** [imageio/imageio#852]
```
$ python -c 'import imageio.v2 as iio, numpy as np; iio.imwrite("/tmp/out.tiff", np.array([[True]]))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/imageio/v2.py", line 228, in imwrite
    raise ValueError("Image is not numeric, but {}.".format(imt.__name__))
ValueError: Image is not numeric, but ndarray.
$ python -c 'import imageio.v3 as iio, numpy as np; iio.imwrite("/tmp/out.tiff", np.array([[True]]))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/imageio/v3.py", line 161, in imwrite
    encoded = img_file.write(image, **kwargs)
  File "/usr/lib/python3.10/site-packages/imageio/core/legacy_plugin_wrapper.py", line 193, in write
    raise ValueError(
ValueError: Image is not numeric, but ndarray.
```
Probably you meant to include the dtype of the array into the error message, not the type of the array object itself.

**Comment by FirefoxMetzger** [comment]
@anntzer Could you specify how things are breaking? A quick test didn't reveal any issues with writing bool:

```python
>>> import imageio.v3 as iio
>>> import numpy as np
>>> foo = np.ones((255, 255), dtype=bool)
>>> img_bytes = iio.imwrite("<bytes>", foo, extension=".png")
>>> img_bytes = iio.imwrite("<bytes>", foo, extension=".jpeg") 
>>> img_bytes = iio.imwrite("<bytes>", foo, extension=".tiff") 
```

**Comment by anntzer** [comment]
As of imageio 2.20.0 (or 2.19.5), the last line of your script fails for me:
```
In [1]: >>> import imageio.v3 as iio
   ...: >>> import numpy as np
   ...: >>> foo = np.ones((255, 255), dtype=bool)
   ...: >>> img_bytes = iio.imwrite("<bytes>", foo, extension=".png")
   ...: >>> img_bytes = iio.imwrite("<bytes>", foo, extension=".jpeg") 
   ...: >>> img_bytes = iio.imwrite("<bytes>", foo, extension=".tiff")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [1], in <cell line: 6>()
      4 img_bytes = iio.imwrite("<bytes>", foo, extension=".png")
      5 img_bytes = iio.imwrite("<bytes>", foo, extension=".jpeg") 
----> 6 img_bytes = iio.imwrite("<bytes>", foo, extension=".tiff")

File /usr/lib/python3.10/site-packages/imageio/v3.py:161, in imwrite(uri, image, plugin, extension, format_hint, **kwargs)
    114 """Write an ndimage to the given URI.
    115 
    116 The exact behavior depends on the file type and plugin used. To learn about
   (...)
    150 
    151 """
    153 with imopen(
    154     uri,
    155     "w",
   (...)
    159     extension=extension,
    160 ) as img_file:
--> 161     encoded = img_file.write(image, **kwargs)
    163 return encoded

File /usr/lib/python3.10/site-packages/imageio/core/legacy_plugin_wrapper.py:193, in LegacyPlugin.write(self, ndimage, **kwargs)
    191 ndimage = np.asanyarray(ndimage)
    192 if not np.issubdtype(ndimage.dtype, np.number):
--> 193     raise ValueError(
    194         "Image is not numeric, but {}.".format(imt.__name__)
    195     )
    196 elif self._request.mode.image_mode == "I":
    197     if ndimage.ndim == 2:

ValueError: Image is not numeric, but ndarray.
```
A bit strange that we get different results?!

**Comment by FirefoxMetzger** [comment]
Ah, I found the difference. I was on the PR branch for https://github.com/imageio/imageio/pull/851 . On master I see the same exception.

I think this should indeed be `ndimage.dtype`. That said, I refactored the exceptions in the PR I mentioned above, so I will address this in the same place and kill two birds with one stone :)
