### ISSUE TITLE
ValueError: Could not find a backend to open `50g.exr`` with iomode `wi`

### ISSUE THREAD

**Issue by Bra1nsen** [imageio/imageio#884]
Greetings! I would like to save a 16bit rgb array as `.exr` file.
I use a camera, capturing multiple images for multi exposure fusion (hdr merge).
Iam in the Solarpower buisness. I will predict the hitting radiance with SkyCams.

![zeitstrahl](https://user-images.githubusercontent.com/58213050/192869695-0027a4dc-60d3-4f1a-baf4-3c8eb052cb64.png)

![Screenshot 2022-09-28 211538](https://user-images.githubusercontent.com/58213050/192869713-d2ac79a4-8cc0-4f7a-a508-285015f0f3ff.png)

I would like to continue my work with these 16 bit raw bayer array safed as .exr (.tga would also work)

def exposure_bracket():
	
	picam2 = Picamera2()
	config = picam2.create_still_configuration(raw={"format": "SRGGB12", "size": (2032, 1520)})
	picam2.configure(config)
	
	exposures = [50, 100, 150, 250, 400, 650, 1050, 1700, 2750] # in Microseconds

	for exp in exposures:

		picam2.set_controls({"ExposureTime": exp, "AnalogueGain": 1, "ColourGains": (1.0,1.0)})
		picam2.start()
		time.sleep(0.5)
		array = picam2.capture_array("raw")
		picam2.stop()
		
		array16 = array.view(np.uint16)
		array16 *= 16  # Bump 12-bit range up to 16
		arrayX = array16.astype("float32")

	        imageio.imwrite(f'{exp}g.exr', arrayX)

		rgb_array = np.zeros((760, 1016, 3), dtype=np.uint16)
		rgb_array[:, :, 0] = array16[1::2, 1::2] # red
		# Must avoid overflowing 16-bits in the addition here:
		rgb_array[:, :, 1] = (array16[0::2, 1::2].astype(int) + array16[1::2, 0::2]) / 2 # green
		rgb_array[:, :, 2] = array16[0::2, 0::2] # blue
		rgb_arrayX = rgb_array.astype("float32")

		imageio.imwrite(f'{exp}rgb.exr', rgb_arrayX)

imageio.plugins.freeimage.download()		
exposure_bracket()

**Comment by FirefoxMetzger** [comment]
@Bra1nsen Did you perform the post-installation step of downloading the FreeImage binary ([documentation here](https://imageio.readthedocs.io/en/stable/_autosummary/imageio.plugins.freeimage.html#module-imageio.plugins.freeimage))?

Once installed, the following EXR round-trip of writing an image and reading it back works fine on my end:

```python
import imageio.v3 as iio
import numpy as np

expected = np.full((128, 128, 3), 0.42, dtype=np.float32)
buffer = iio.imwrite("<bytes>", expected, extension=".exr")

actual = iio.imread(buffer)

np.allclose(actual, expected)
```

**Comment by Bra1nsen** [comment]
I thought I could just the function `imageio.plugins.freeimage.download()`	. I use a Raspberry Pi4, how to install?

Thats my current code with your snippet..

```
import numpy as np
from picamera2 import Picamera2
from numpy import save
import imageio
import imageio.v3 as iio
	
imageio.plugins.freeimage.download()	
picam2 = Picamera2()
config = picam2.create_still_configuration(raw={"format": "SRGGB12", "size": (2032, 1520)})
picam2.configure(config)
	
picam2.set_controls({"ExposureTime": 80, "AnalogueGain": 1, "ColourGains": (1.0,1.0)})
picam2.start()
time.sleep(0.5)
array = picam2.capture_array("raw")
picam2.stop()
		
array16 = array.view(np.uint16)
array16 *= 16  # Bump 12-bit range up to 16
arrayX = array16.astype("float32")
iio.imwrite("test", arrayX, extension=".exr")

```

I just would like to save the array as .exr ..

```
/usr/local/lib/python3.9/dist-packages/imageio/plugins/pillow.py:98: UserWarning: Can't determine file format to write as. You _must_ set `format` during write or the call will fail. Use `extension` to supress this warning. 
  warnings.warn(
Traceback (most recent call last):
  File "/home/pi/testrawbayer/pyTGA/thesh1t/x.py", line 36, in <module>
    iio.imwrite("test", arrayX, extension=".exr")
  File "/usr/local/lib/python3.9/dist-packages/imageio/v3.py", line 161, in imwrite
    encoded = img_file.write(image, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/imageio/plugins/pillow.py", line 292, in write
    "format": format or Image.registered_extensions()[extension],
KeyError: None
```

**Comment by FirefoxMetzger** [comment]
@Bra1nsen Indeed, `imageio.plugins.freeimage.download()` should download the library. If you take the snippet I posted above and run it on your raspberry pi, does it finish cleanly or does it produce an exception?

The exception you shared here indicates that the library is selecting the pillow backend to write (which is strange, because it can't write EXR...). Apart from the test above, could you try to change your last line to

```python
iio.imwrite("test.exr", arrayX, plugin="EXR-FI")
```

and let me know what that does?

**Comment by Bra1nsen** [comment]
```
mageio.core.request.InitializationError: `EXR-FI` can not write to `test`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/testrawbayer/pyTGA/thesh1t/x.py", line 36, in <module>
    iio.imwrite("test", arrayX, plugin="EXR-FI")
  File "/usr/local/lib/python3.9/dist-packages/imageio/v3.py", line 153, in imwrite
    with imopen(
  File "/usr/local/lib/python3.9/dist-packages/imageio/core/imopen.py", line 165, in imopen
    raise err_type(err_msg) from err_from
OSError: `EXR-FI` can not handle the given uri.

```

thanks for you help Firefox..

**Comment by Bra1nsen** [comment]
anythingelse I could try?

**Comment by Bra1nsen** [comment]
hey firefox. I just tried you snippet:

```
Exception ignored in: <function PluginV3.__del__ at 0xb4f13d18>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/imageio/core/v3_plugin_api.py", line 367, in __del__
    self.close()
  File "/usr/local/lib/python3.9/dist-packages/imageio/core/v3_plugin_api.py", line 354, in close
    self.request.finish()
  File "/usr/local/lib/python3.9/dist-packages/imageio/core/request.py", line 551, in finish
    bytes = Path(self._filename_local).read_bytes()
  File "/usr/lib/python3.9/pathlib.py", line 1248, in read_bytes
    with self.open(mode='rb') as f:
  File "/usr/lib/python3.9/pathlib.py", line 1241, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.9/pathlib.py", line 1109, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/imageio_gx2ec4ep.exr'
```

**Comment by baoachun** [comment]
I also encountered this problem.
```
writer = imageio.get_writer(f'{out_dir}/{mp4save_fn}', mode='I', fps=30, codec='libx264', bitrate='16M')
```
<img width="822" alt="image" src="https://user-images.githubusercontent.com/22114318/226549335-98c92b28-ca54-4c5d-a844-d6d871ad2425.png">
