### ISSUE TITLE
Trouble writing gif with v3 interface

### ISSUE THREAD

**Issue by ryancoe** [imageio/imageio#895]
I tried running the example code here (below also): https://imageio.readthedocs.io/en/stable/examples.html#optimizing-a-gif-using-pygifsicle

```python
import imageio.v3 as iio
import matplotlib.pyplot as plt
import numpy as np
from pygifsicle import optimize

n = 100
gif_path = "test.gif"
frames_path = "{i}.jpg"

n = 100
plt.figure(figsize=(4,4))
for x in range(n):
    plt.scatter(x/n, x/n)
    plt.xlim(0, 1)
    plt.ylim(0, 1)
    plt.savefig(f"{x}.jpg")

frames = np.stack(
    [iio.imread(f"{i}.jpg") for i in range(n)],
    axis=0
)

iio.imwrite(gif_path, frames, mode="I")

optimize(gif_path)
```

I get the following error message:

```
Traceback (most recent call last):
  File "/Users/rcoe/Downloads/iio.py", line 22, in <module>
    iio.imwrite(gif_path, frames, mode="I")
  File "/Users/rcoe/anaconda3/envs/iio/lib/python3.10/site-packages/imageio/v3.py", line 161, in imwrite
    encoded = img_file.write(image, **kwargs)
  File "/Users/rcoe/anaconda3/envs/iio/lib/python3.10/site-packages/imageio/plugins/pillow.py", line 323, in write
    pil_frame = Image.fromarray(frame, mode=mode)
  File "/Users/rcoe/anaconda3/envs/iio/lib/python3.10/site-packages/PIL/Image.py", line 2965, in fromarray
    raise ValueError(f"Too many dimensions: {ndim} > {ndmax}.")
ValueError: Too many dimensions: 3 > 2.
```

<details>
  <summary>conda environment</summary>

```yml
name: iio
channels:
  - defaults
  - conda-forge
dependencies:
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2022.07.19=hca03da5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hd633e50_0
  - imageio=2.22.0=pyhfa7a67d_0
  - jpeg=9e=he4db4b2_2
  - kiwisolver=1.4.2=py310hc377ac9_0
  - lcms2=2.12=had6a04f_0
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.14=h1a8c8d9_0
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_25
  - libgfortran5=11.3.0=hdaf2cc0_25
  - liblapack=3.9.0=16_osxarm64_openblas
  - libopenblas=0.3.21=openmp_hc731615_3
  - libpng=1.6.38=h76d750c_0
  - libsqlite=3.39.4=h76d750c_0
  - libtiff=4.4.0=hfa0b094_4
  - libwebp-base=1.2.4=h57fd34a_0
  - libxcb=1.13=h9b22ae9_1004
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=14.0.4=hd125106_0
  - matplotlib=3.5.2=py310hca03da5_0
  - matplotlib-base=3.5.2=py310hc377ac9_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h07bb92c_1
  - numpy=1.23.4=py310h5d7c261_0
  - openjpeg=2.5.0=h5d4e404_1
  - openssl=3.0.5=h03a7124_2
  - packaging=21.3=pyhd3eb1b0_0
  - pillow=9.2.0=py310h173adc3_2
  - pip=22.3=pyhd8ed1ab_0
  - pthread-stubs=0.4=h27ca646_1001
  - pyparsing=3.0.9=py310hca03da5_0
  - python=3.10.6=hae75cb6_0_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - readline=8.1.2=h46ed386_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - six=1.16.0=pyhd3eb1b0_1
  - tk=8.6.12=he1e0b03_0
  - tornado=6.2=py310h1a28f6b_0
  - tzdata=2022e=h191b570_0
  - wheel=0.37.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h27ca646_0
  - xorg-libxdmcp=1.1.3=h27ca646_0
  - xz=5.2.6=h57fd34a_0
  - zstd=1.5.2=h8128057_4
  - pip:
    - pygifsicle==1.0.6
    - support-developer==1.0.4
```

</details>

**Comment by FirefoxMetzger** [comment]
Good catch. Matplotlib saves the image as RGB; however, we are instructing ImageIO to treat the input as grayscale (`mode="I"`). You have two options:

1. Remove `mode="I"` in `iio.imwrite(gif_path, frames, mode="I")`. This will create a RGB GIF.
2. Add `mode="I"` in `[iio.imread(f"{i}.jpg", mode="I") for i in range(n)]`. This will create a grayscale GIF.

Which one to choose depends on your scenario. For our example, I think a RGB gif makes the most sense, because it makes things more visual.

@ryancoe Would you be interested in submitting a PR to update this in our docs?

**Comment by ryancoe** [comment]
Thanks for the very prompt response @FirefoxMetzger!
