### ISSUE TITLE
RuntimeError: `FFMPEG` can not handle the given uri.

### ISSUE THREAD

**Issue by DavidTadres** [imageio/imageio#900]
The error seems to originate from imageio as an older version of imageio (2.9.0) doesn't throw the same error and does behave as expected. However a newer version (currently 2.19.3) returns the error.

Minimal WORKING example (test file can be found here: https://drive.google.com/file/d/1QiiHzg6DV0U9yfApnBr1OoTYMTiiadbz/view?usp=sharing). The example below were tested on the same PC (Windows 10) in parallel.

```
conda create -n imageio_working_env -y

activate imageio_working_env

conda install imageio=2.9.0
pip install imageio-ffmpeg

python

import imageio

video_object = imageio.get_reader('test_Video.h264', 'ffmpeg')
```

Minimal NOT working example (same file as above)

```
conda create -n imageio_broken_env -y

activate imageio_broken_env

conda install imageio # installs: pkgs/main/win-64::imageio-2.19.3-py310haa95532_0 None
pip install imageio-ffmpeg

python

import imageio

video_object = imageio.get_reader('test_Video.h264', 'ffmpeg')

Traceback (most recent call last):
  File "C:\Users\tadres\Miniconda3\envs\imageio_broken_env\lib\site-packages\imageio\core\imopen.py", line 147, in imopen
    return loader(request, **kwargs)
  File "C:\Users\tadres\Miniconda3\envs\imageio_broken_env\lib\site-packages\imageio\core\imopen.py", line 135, in loader
    return config.plugin_class(request, **kwargs)
  File "C:\Users\tadres\Miniconda3\envs\imageio_broken_env\lib\site-packages\imageio\config\plugins.py", line 107, in partial_legacy_plugin
    return LegacyPlugin(request, legacy_plugin)
  File "C:\Users\tadres\Miniconda3\envs\imageio_broken_env\lib\site-packages\imageio\core\legacy_plugin_wrapper.py", line 79, in __init__
    raise InitializationError(
imageio.core.request.InitializationError: `FFMPEG` can not read `test_Video.h264`.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\tadres\Miniconda3\envs\imageio_broken_env\lib\site-packages\imageio\v2.py", line 133, in get_reader
    image_file = imopen(uri, "r" + mode, **imopen_args)
  File "C:\Users\tadres\Miniconda3\envs\imageio_broken_env\lib\site-packages\imageio\core\imopen.py", line 165, in imopen
    raise err_type(err_msg) from err_from
RuntimeError: `FFMPEG` can not handle the given uri.
```

**Comment by DavidTadres** [comment]
@FirefoxMetzger Wow, thank you for the rapid response and for solving the problem. I also really appreciate the tip of using imageio.v3.

**Comment by FirefoxMetzger** [comment]
@DavidTadres No worries. FYI, the PR will be part of next week's release.
