### ISSUE TITLE
AttributeError: n_frames

### ISSUE THREAD

**Issue by petsuter** [imageio/imageio#958]
```
>>> from imageio.v3 import improps
>>> improps(r"test_libuemf_ref.emf")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python311\Lib\site-packages\imageio\v3.py", line 198, in improps
    properties = img_file.properties(**call_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\imageio\plugins\pillow.py", line 455, in properties
    n_frames: int = self._image.n_frames
                    ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\PIL\Image.py", line 529, in __getattr__
    raise AttributeError(name)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: n_frames
```

 imageio 2.26.0, Pillow  9.4.0

(The test file can be downloaded e.g. here: https://github.com/mathog/libUEMF/blob/master/test_libuemf_ref.emf)

**Comment by radarhere** [comment]
I've created PR #984 as a possible fix for this.

**Comment by FirefoxMetzger** [comment]
Oh wow, this issue went completely under my radar; I must have missed a notification somewhere. Sorry for not responding sooner @petsuter !

Also thanks for the fix @radarhere I will have a look at the PR soon.
